MinishLab/model2vec

model2vec/model.py
This PR adds a speed optimization:
For longer texts, tokenization can take up 90-95% of our time, because we tokenize the entire text. However, we usually only take the first N (usually 512) tokens of text. So, it makes sense to only really tokenize the first X tokens of a text. We therefore truncate texts to N * median(token_lengths). A test on wikipedia shows that this doesn't lead to any unnecessary truncation, i.e., it never truncated to a length < 512 tokens.
=> Add median token length as limit

model2vec/model.py
Config currently wasn't optional. Since we allow it to be empty, we just make it optional and turn it into an empty dict
=> fix: make config optional

model2vec/model.py, tests/test_model.py
Sometimes we need an easy way to know the dimensionality of our model (👀 ). This used to be hard, now it's easy with a nice property.
=> enh: add dim property

model2vec/distill/distillation.py, model2vec/distill/inference.py, model2vec/model.py
The `bos_token_id` and `eos_token_id` appear to be reversed in the `create_output_embeddings_from_model_name` function within `model2vec/distill/inference.py`.
When I testing with following code
```python
from transformers import AutoModel, AutoTokenizer
from model2vec.distill import distill_from_model
model_name = "bert-base-uncased"
model = AutoModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)
m2v_model = distill_from_model(model=model, tokenizer=tokenizer, pca_dims=256)
```
before the fix `bos_token_id` is `102` and `eos_token_id` is `101` but for BERT tokenizer the correct `bos_token_id` and `eos_token_id` should be
```python
>>> tokenizer.cls_token_id
101
>>> tokenizer.sep_token_id
102
```
=> Fix distill model bos and eos token

.gitignore, README.md, results/README.md
- Moved results to a different readme
- Added blog link 
- Swapped "main features" and "what is model2vec" sections
- Small updates
=> docs: Move results and add blogpost

model2vec/model.py
We didn't move the tensor to cpu before trying to dump it, which causes an error if the model is on another device.
=> fix: move tensor to cpu

model2vec/model.py, pyproject.toml
A newer version of tokenizers introduced faster tokenizers, shaves about 5-10% off.
=> feat: faster tokenization

model2vec/distill/distillation.py
This PR adds a simple message logging the explained variance. Users can use this to decide whether they went too far.
=> enhancement: Add explained variance messages

model2vec/distill/inference.py
Reverting a change from https://github.com/MinishLab/model2vec/commit/97d367795239de23f2020a9b8d3a30c87075a660. After testing, it turns out that having them reversed works better on our benchmarks. We plan to investigate this further.
=> fix: Reverted eos bos change

model2vec/distill/tokenizer.py
This fixes #106 .
We were overfitting on berttokenizer, apparently roberta has a different structure. this fix works for roberta and bert.
=> fix: update added tokens to be more agnostic

model2vec/distill/inference.py
=> fix: don't rely on reported vocab size, log warning if inconsistent

model2vec/model.py, tests/conftest.py, tests/test_model.py
If tokenizers < 0.20 is installed the code can still work, but we need a flag to know which function to call. I think this is worth supporting, because 0.20 is relatively new.
=> feat: make encode_batch_fast optional

model2vec/model.py, model2vec/utils.py, pyproject.toml, tests/test_model.py, uv.lock
Some simple code for benchmarking:
```python
from time import perf_counter
from model2vec import StaticModel
from datasets import load_dataset
def main(use_multiprocessing: bool):
ds = load_dataset(
"wikimedia/wikipedia",  
data_files="20231101.en/train-00000-of-00041.parquet"
)["train"]
texts = ds["text"]
model = StaticModel.from_pretrained("minishlab/potion-base-8M")
start = perf_counter()
output = model.encode(
sentences=texts, 
show_progress_bar=True, 
use_multiprocessing=use_multiprocessing,
)
total_time = perf_counter() - start
docs_per_second = len(texts) / total_time
print(f"Processed {len(texts)} docs in {total_time:.3f}s.")
print(f"Docs per second: {docs_per_second:.2f}")
print("Output shape:", output.shape)
if __name__ == "__main__":
print("Multiprocessing=False") …
```
=> feat: Add multiprocessing

model2vec/distill/distillation.py, model2vec/distill/inference.py, uv.lock
=> docs: fix docstrings in distill

model2vec/hf_utils.py
Noted by #160, we import `huggingface_hub.errors`, but this doesn't do anything.
=> remove unnecessary import

model2vec/model.py
I noticed the `normalize` wasn't added to the class methods so I added it.
=> feat: Add optional embedding normalization to StaticModel loading

model2vec/train/README.md
Scores were in weird order, mean was missing for setfit
=> fix scores in readme

model2vec/train/classifier.py
This PR exposes min_epochs and max_epochs for fit. This is a bit more flexible (e.g. when you want to train a test model for 1 epoch, this is currently not possible). max_epochs defaults to -1, meaning it will run until early stopping is triggered.
=> feat: Added min and max epochs to fit

model2vec/inference/model.py, model2vec/train/classifier.py, tests/test_inference.py, uv.lock
This PR adds multilabel targets to the inference pipeline, and also fixes the tests so that this works. 
I think the test solution is a bit ugly.
=> feat: add multilabel targets to inference pipeline, fix tests

model2vec/modelcards/classifier_template.md, model2vec/modelcards/model_card_template.md
The model card template had outdated links, and didn't include an example for sentence transformers yet. The citation format was also incorrect. This PR fixes that. Also made a few minor updates to the text.
=> docs: Update model card template

README.md, model2vec/inference/__init__.py, model2vec/inference/model.py, model2vec/train/README.md, model2vec/train/classifier.py, tests/conftest.py, tests/test_inference.py, tests/test_trainable.py, uv.lock
This PR adds an `evaluate` function that can be used after fitting a classifier. It returns an sklearn classification report. It works for both multi and single label inputs, and str and int type labels. This makes it a bit easier to evaluate a model by abstracting away the logic for binarizing labels in the multilabel case, and in general provides a nice natural flow, e.g.:
```python
classifier = StaticModelForClassification.from_pretrained(model_name="minishlab/potion-base-32M")
ds = load_dataset("setfit/subj")
classifier.fit(ds["train"]["text"], ds["train"]["label"], max_epochs=1)
print(classifier.evaluate(ds["test"]["text"], ds["test"]["label"]))
```
The tests are also updated to include int type labels. While our typing doesn't officially support list[int], many of the datasets we …
=> feat: Add evaluate function for classifiers

model2vec/train/README.md, model2vec/train/base.py, tests/test_trainable.py
#199 shows that it is confusing that out_dim comes before the model_name in `from_pretrained`. So fix this, I switched to only allowing named arguments in `from_pretrained`. I explicitly did not change it in the other parts of the code base because confusion is less apparent there.
=> fix: only allows named args in pretrain

model2vec/knowledge_distill/featurize.py, model2vec/knowledge_distill/knowledge_distillation.py, model2vec/knowledge_distill/utils.py
This PR fixes some issues and makes the code a bit more similar to the classifier code. Once this is merged, I'll remove a lot of it because of the new tokenlearn.
=> feat: styling, fixing some bugs

tutorials/semantic_chunking.ipynb
Add "chonkie[semantic]" to the installs and add the new chunking params during init of the `SemanticChunker`. Also use `potion-base-32M` for improved chunk quality. 
This pull request includes updates to the `tutorials/semantic_chunking.ipynb` file to improve the tutorial's functionality and performance. The most important changes include updating the library installation command, modifying the model used for chunking, and adjusting the execution counts and outputs for various cells.
Library and model updates:
* Updated the library installation command to include the `chonkie[semantic]` package.
* Changed the embedding model from `minishlab/potion-base-8M` to `minishlab/potion-base-32M` and adjusted chunking parameters for better performance.
Execution counts and outputs:
* Updated …
=> fix: Updated semantic chunking tutorial 

model2vec/distill/distillation.py, model2vec/distill/inference.py, model2vec/distill/tokenizer.py, model2vec/distill/utils.py, tests/conftest.py, tests/test_distillation.py, uv.lock
This PR completely rewrites the distill backend.
* There's no longer a difference between subword and vocabulary inference
* BPE and unigram tokenizer token removal/addition is supported
* All tokenizers now take into account normalization when adding tokens
* Tokens that are multi-word units are no longer allowed
* Make tokenizers a bit smaller by removing unneeded special tokens
=> rewrite backend

model2vec/distill/distillation.py
This fixes the issue with the vocabulary from #209
=> fix: pretokenize tokens before checking vocabulary

model2vec/distill/distillation.py, model2vec/model.py, model2vec/quantization.py, scripts/export_to_onnx.py, tests/test_model.py, tests/test_quantization.py
This PR adds quantization. Quantization can be applied during distillation, or during loading. Both are equivalent, except that distill-time quantization leads to smaller embedding sizes.
=> feat: add quantization

model2vec/model.py, model2vec/quantization.py
This PR removes the flag argument in the load function and moves the quantization business to another function.
=> feat: remove flag argument

model2vec/distill/distillation.py, model2vec/distill/inference.py, model2vec/distill/tokenizer.py, model2vec/distill/utils.py
Fixes #209 (again 😓 )
This PR adds a `Token` class to keep track of whether a token was originally a subword or added token. If it was a subword token, we should not pretokenize it. Previously, we relied on whether a token was in the original vocabulary, but this turned out to not work for unigram tokenizers with a metaspace if the token was also a subword token.
For "ELLE", for example: 
1. Check if "ELLE" is in vocab, we pretokenize it to "_ELLE". This is fine
2. Then, when adding it, we need to check whether it is a subword. But "ELLE" is also a subword.
3. So we don't pretokenize it before adding it, causing us to add two tokens with the same surface form.
=> feat: track token provenance

model2vec/inference/model.py, model2vec/model.py
Small typing issues: we actually accept non-list sequences in almost all our functions, but type them as list. This should be Sequence[str]. Since str is also Sequence[str], we can just use a single type in most places, and no longer have to use a union.
Inference pipeline saving was broken (my bad)
=> fix: typing issues, bug in infernece

model2vec/distill/distillation.py, model2vec/distill/inference.py, model2vec/distill/tokenizer.py, model2vec/distill/utils.py, tests/test_distillation.py
Some tokenizers use `<|endoftext|>` or other tokens as PAD token, this breaks the assumption in `StaticModelForClassification`.
Fixes #223
=> fix: issues with unk and pad

model2vec/train/base.py
Using a half precision or int8 model would break training.
Half precision only breaks on CPU, but int8 always breaks, because int8 embeddings are not supported in pytorch.
=> fix: precision during training

model2vec/distill/tokenizer.py
The unk token wasn't correctly set for unigram. This led to correct initialization, but would break if an unk was ever encountered. This is rare, which is why I didn't spot it before.
=> fix: issue with unk in unigram

model2vec/inference/model.py
The `push_to_hub` `subfolder` argument was mistyped as `str` and didn't take `None` as a default argument. This adds `str | None` as the type, and `None` as a default.
=> fix: add default arg for push_to_hub

model2vec/distill/distillation.py, model2vec/hf_utils.py
This PR removes direct dependency on specific huggingface-hub errors. These were in different submodules for different versions, so we had conditional imports. Additionally, there are other reasons a hf hub transfer can fail (e.g, internet access failing during an active python session), so just catching the hf hub errors might not be enough.
=> fix: remove direct dependency on specific hf utils

model2vec/train/classifier.py, tests/test_trainable.py
i have been experimenting with model2vec and it is great! kudos for the awesome work
I wanted to use my own validation set but that was not exposed, this PR simply adds optional arguments to the `fit` method to allow passing your own validation data
=> feat: allow passing validation set explicitly

model2vec/distill/distillation.py
was failing to distill models that didn't include a model card in huggingface
```bash
fdemelo/xlm-roberta-ovos-intent-classifier
Some weights of XLMRobertaModel were not initialized from the model checkpoint at fdemelo/xlm-roberta-ovos-intent-classifier and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Encoding tokens: 100%|██████████| 249999/249999 [03:34<00:00, 1165.90 tokens/s]
Traceback (most recent call last):
File "/home/miro/PycharmProjects/NLP/distilintent/distill.py", line 124, in <module>
m2v_model = distill(model_name=m, pca_dims=256)
File "/home/miro/PycharmProjects/model2vec/model2vec/distill/distillation.py", line 239, in distill
return …
```
=> fix: distillation for models without card

model2vec/tokenizer/normalizer.py
This PR normalizes the spacing dependent on how the original tokenizer does it. This is important to retain performance increase for BPE and non-BPE tokenizers.
=> feat: make normalization dependent on spacing

model2vec/train/classifier.py, tests/test_trainable.py
I wanted to be able to pass along a weight Tensor to better handle working with imbalanced class data.
=> add support for passing weight to the loss functions

.github/workflows/ci.yaml, Makefile, pyproject.toml
This PR adds Python 3.13 to our pyproject supported languages and to CI. Many of our downloads come from 3.13 now but we don't "officially" test/support it right now.
=> chore: Added python 3.13 to pyproject and CI

model2vec/distill/inference.py, model2vec/hf_utils.py, model2vec/model.py, model2vec/utils.py, tests/test_model.py, tests/test_utils.py, uv.lock
This PR adds much faster model loading by directly loading from cache if a model is cached, if `force_download` is set to true during loading
Timings when loading `potion-base-8m`
* Before: 1.27 s ± 72.5 ms per loop
* Now: 37.3 ms ± 335 µs per loop
This speed is only enabled when setting `force_download` to `False`. It is true by default for backwards compatibility and download tracking
Mention for #275
=> feat: faster loading if model already cached

model2vec/hf_utils.py, model2vec/model.py, tests/test_model.py
This PR adds the used vocabulary_quantization and embedding_dtype for quantization to the config, which makes it easier to see the precision of the model and (optionally) number of clusters for the vocabulary directly from the config. 
E.g.:
```json
{
"model_type": "model2vec",
"architectures": [
"StaticModel"
],
"tokenizer_name": "baai/bge-base-en-v1.5",
"apply_pca": 256,
"apply_zipf": true,
"hidden_dim": 256,
"seq_length": 1000000,
"normalize": true,
"vocabulary_quantization": 128,
"embedding_dtype": "float16"
}
```
=> feat: Added embedding_dtype and vocabulary_quantization to config

model2vec/distill/utils.py, tests/test_utils.py
Torch shows significant drops in performance across tasks when distilling with MPS on version 2.8.0. For this reason, it's disabled until this has been resolved in Torch.
=> fix: Disable MPS for Torch versions >=2.8.0

model2vec/distill/distillation.py, model2vec/distill/inference.py, tests/test_distillation.py
Aligns better with Sentence Transformers.
=> chore: Rename PoolingType to PoolingMode
